[project]
name = "vision-herrajes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "av",
    "joblib",
    "numpy",
    "opencv-python",
    "Pillow",
    "python-snap7>=2.0.2",
    "scikit-image",
    "scikit-learn",
    "tqdm",
    "vision-defect-detection",
]

[project.scripts]
classify = "src.cli:run_classify"
"classify-camera" = "src.cli:run_classify_camera"
"tune-gui" = "src.cli:run_tuner"
"front-final" = "src.cli:run_front_final"

[tool.uv.sources]
vision-defect-detection = { path = "vision_defect_detection-0.1.0-py3-none-any.whl" }

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
